# Generated by Django 3.2.9 on 2021-12-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20211206_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='forecast',
            name='icon',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
