# Generated by Django 3.2.9 on 2021-12-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
    ]
